"""Add middle_name to Student model

Revision ID: 323ce26b8ba6
Revises: 
Create Date: 2025-06-12 12:01:12.577616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323ce26b8ba6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('middle_name', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('middle_name')

    # ### end Alembic commands ###
